### ISSUE TITLE
Mailpile 1.0.0rc5

### ISSUE THREAD

**Issue by blfpd** [rroemhild/docker-mailpile#11]
Could you make [Mailpile 1.0.0rc5 ](https://github.com/mailpile/Mailpile/releases/tag/1.0.0rc5)happen, please? :slightly_smiling_face: 

Commit: https://github.com/mailpile/Mailpile/commit/e64e27ca4a35fab44538cae5c1edd0d1d8c0d6ca

**Comment by rroemhild** [comment]
Done

**Comment by blfpd** [comment]
Awesome, thank you so much!
