### ISSUE TITLE
Persistent data volume binding

### ISSUE THREAD

**Issue by eggfriedrice** [rroemhild/docker-mailpile#2]
Hi

Thanks for this Dockerfile, it works fine. The only problem I have is the volume binding.

I've tried binding `/root/.local/share/Mailpile` (from the Readme) and the `/mailpile-data/.local/share/Mailpile` and `/mailpile-data/.gnupg` volumes in the Dockerfile, but neither seems to work.

Can you give an example docker command so I can check I'm not doing something stupid?

Cheers,
Al

**Comment by kode54** [comment]
The Dockerfile specifies paths of /mailpile-data, but you really want /root. And you need to specify:

```-v /some/local/path:/root/.local/share/Mailpile -v /another/local/path:/root/.gnupg```
